export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_PHONE = "SET_USER_PHONE";
export const SET_USER_OTP = "SET_USER_OTP";
export const SET_USER_OLD_PASSWORD = "SET_USER_OLD_PASSWORD";
export const SET_USER_NAME = "SET_USER_NAME";
export const SET_USER_BIRTHYEAR = "SET_USER_BIRTHYEAR";
export const SET_USER_COUNTRY = "SET_USER_COUNTRY";
export const SET_USER_PINCODE = "SET_USER_PINCODE";
